org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.19.3
loom_version=1.14.7

mod_version=1.0.0-1.21.1
maven_group=Yeah_Zero.Subtitle_Highlight
archives_base_name=Subtitle-Highlight

fabric_api_version=0.116.13+1.21.1
modmenu_version=11.0.4
cloth_config_version=15.0.140
