org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.19.3
loom_version=1.16-SNAPSHOT

mod_version=1.0.0-1.21.10
maven_group=Yeah_Zero.Subtitle_Highlight
archives_base_name=Subtitle-Highlight

fabric_api_version=0.138.4+1.21.10
modmenu_version=16.0.1
cloth_config_version=20.0.149
